### ISSUE TITLE
Не загружать изображения, которые не видны на экране

### ISSUE THREAD

**Issue by funtom48** [xtsmi/aggregator#2]
Начинать грузить изображения, когда до новости остается +/- 500px
Или придумать что то другое

**Comment by tabuna** [comment]
@funtom48 Добавил к каждому изображению атрибут `loading`:

```html
<img src="image.jpg" loading="lazy" alt="..." />
```
Возможно это должно нативно решить проблему. Можно прочитать тут:
https://developer.mozilla.org/ru/docs/Web/Performance/Lazy_loading

**Comment by funtom48** [comment]
@tabuna да, аттрибут помогает.
